import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,UsersThree,MapTrifold,Eye,Minus,Plus,Pause,Play,Hand,ArrowCounterClockwise,X,ListChecks,Coins,ClockCounterClockwise,Chair,ArrowUp,ArrowDown} from '@phosphor-icons/react';
import {CityScene} from './CityScene.jsx';
import {TYNYSH_MENUS,tynyshMoney,tynyshTotals,tableGuests} from './tynyshDemo.js';
import {TYNYSH_TABLES,TYNYSH_STAFF} from './tynyshLayout.js';
import './tynysh.css';

const tabs=[['plan','План',Chair],['tasks','Подготовка',ListChecks],['finance','Финансы',Coins],['history','История',ClockCounterClockwise]];
function Booking({state,dispatch}){
  return <form className="ty-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);dispatch({type:'BOOK',title:data.get('title'),date:data.get('date'),guests:data.get('guests')});}}><h3>Новый банкет</h3><p>18 октября зал занят. На 19 октября есть свободное место.</p><label>Название<input required maxLength={60} name="title" defaultValue="Семейный банкет"/></label><div className="ty-fields"><label>Дата<input required type="date" name="date" defaultValue="2026-10-18"/></label><label>Гостей<input required type="number" min="6" max="48" name="guests" defaultValue="48"/></label></div><button className="ty-primary" type="submit">Подтвердить бронь<ArrowRight size={16}/></button><small>Новая бронь начнёт подготовку заново. Текущий банкет: {state.event.date}.</small></form>;
}
function Payment({dispatch}){
  return <form className="ty-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);dispatch({type:'PAYMENT',kind:data.get('kind'),amount:data.get('amount'),label:data.get('label')});}}><h3>Добавить операцию</h3><label>Тип<select name="kind" defaultValue="income"><option value="income">Поступление</option><option value="expense">Расход</option></select></label><label>Назначение<input required maxLength={60} name="label" placeholder="Например, оплата банкета"/></label><label>Сумма, ₸<input required type="number" min="1" max="10000000" name="amount"/></label><button type="submit" className="ty-primary">Добавить<Plus size={17}/></button></form>;
}
export function TynyshExperience({state,dispatch,director,onLeave,onPortfolio}){
  const api=useRef(null),dialog=useRef(null),returnFocus=useRef(null),[panel,setPanel]=useState(null),[top,setTop]=useState(false),[zoom,setZoom]=useState(100),[card,setCard]=useState(true),[notice,setNotice]=useState('');
  const [bot,setBot]=useState({name:'Данияр',text:'Команда готовит зал',progress:0,done:0,total:3});
  const ready=state.tasks.filter(t=>t.done).length,total=tynyshTotals(state),admin=state.role==='admin';
  const selected=state.tasks.find(t=>t.table===state.selected),member=TYNYSH_STAFF.find(a=>a.id===selected.staff);
  useEffect(()=>{document.title='Tynysh · Банкетный зал | Елнур';},[]);
  useEffect(()=>{if(!panel)return;returnFocus.current=document.activeElement;dialog.current?.showModal();return()=>{dialog.current?.close();returnFocus.current?.focus?.();};},[!!panel]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3200);return()=>clearTimeout(timer);},[notice]);
  const showPanel=id=>setPanel(state.role==='staff'?'tasks':id);
  function select(id,open=false){dispatch({type:'SELECT',table:id});setCard(true);if(open)showPanel('plan');}
  function takeControl(){dispatch({type:'CONTROL',mode:'manual',paused:true});showPanel('plan');}
  function togglePause(){if(state.phase==='seating'){dispatch({type:'PREPARE'});return;}dispatch({type:'CONTROL',paused:!state.automation.paused});}
  return <main className="tynysh-stage" aria-label="Банкетный зал Tynysh">
    <CityScene api={api} location="tynysh" cameraMode="overview" overview={false} inputEnabled={!panel} status="В зале" director={director} tynyshDemo={state} onBotEvent={dispatch} onBotView={setBot} onAction={a=>a.type==='exit'?onLeave():a.type==='table'?select(a.table,true):null} onProject={id=>{if(id.startsWith('table-'))select(Number(id.slice(6)),true);}} onNotice={setNotice} onWalk={()=>{}} onView={v=>setZoom(v.zoom)}/>
    <header className="ty-header">
      <nav className="ty-home ty-glass" aria-label="Навигация проекта"><button onClick={onLeave}><ArrowLeft size={20}/><span>В город</span></button><button className="ty-brand" onClick={()=>onPortfolio({mode:'resume',project:'tynysh'})}>Tynysh</button><span className="ty-badge">Демо</span></nav>
      <ol className="ty-steps ty-glass" aria-label="Этапы банкета">{['Бронь','Рассадка','Подготовка','Готово'].map((label,i)=>{const step=state.phase==='seating'?1:state.phase==='ready'?3:2;return <li key={label} aria-label={label} aria-current={i===step?'step':undefined} className={i<step?'complete':i===step?'current':''}><span>{i<step?<Check size={15} weight="bold"/>:i+1}</span><b>{label}</b></li>;})}</ol>
      <div className="ty-camera"><button className="ty-glass" aria-label={top?'Обзор зала':'Вид сверху'} onClick={()=>{setTop(!top);api.current?.setRoomTop(!top);}} aria-pressed={top}>{top?<Eye size={19}/>:<MapTrifold size={19}/>}<span>{top?'Обзор зала':'Вид сверху'}</span></button><div className="ty-zoom ty-glass"><button aria-label="Уменьшить масштаб" disabled={zoom<=65} onClick={()=>api.current?.zoom(-.1)}><Minus size={17}/></button><span>{zoom}%</span><button aria-label="Увеличить масштаб" disabled={zoom>=210} onClick={()=>api.current?.zoom(.1)}><Plus size={17}/></button></div></div>
    </header>
    <button className="ty-event" onClick={()=>showPanel('plan')}><UsersThree size={23} weight="fill"/><span><strong>Банкет на {state.event.guests} гостей</strong><small>{new Date(state.event.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})} · {ready} из 6 столов готовы</small></span></button>
    {card&&!panel&&<section className="ty-worker ty-glass" aria-label="Текущая задача"><button className="ty-close" aria-label="Скрыть подсказку" onClick={()=>setCard(false)}><X size={17}/></button><div className="ty-worker-head"><img className="ty-worker-icon" src="/textures/tynysh-staff-avatar.png" alt="" width="42" height="45"/><div><strong>{state.phase==='ready'?'Всё готово':bot.name}</strong><p>{bot.text}</p></div></div><progress aria-label="Прогресс подготовки сотрудника" value={bot.progress||0} max="1"/><small>{state.phase==='ready'?'6 столов · гости могут проходить':`${bot.done||0} из ${bot.total||3} задач выполнено`}</small><button className="ty-worker-link" onClick={()=>setPanel('tasks')}><ListChecks size={20}/>Открыть задачи<ArrowRight size={17}/></button></section>}
    <div className="ty-bottom">
      <p className="ty-keys ty-glass"><kbd>WASD</kbd> — ходить<span>·</span><kbd>E</kbd> — выбрать</p>
      <div className="ty-playbar ty-glass"><button className="ty-play" aria-label={state.automation.paused?'Продолжить подготовку':'Приостановить подготовку'} disabled={state.phase==='ready'||(!admin&&state.phase==='seating')} onClick={togglePause}>{state.automation.paused||state.phase==='seating'?<Play size={21} weight="fill"/>:<Pause size={21} weight="fill"/>}</button><strong>{state.phase==='ready'?'Зал готов':state.phase==='seating'?'Рассадка гостей':state.automation.paused?'Подготовка на паузе':'Команда готовит зал'}</strong><div className="ty-speed">{[1,2].map(n=><button key={n} aria-label={`Скорость ${n}×`} aria-pressed={state.automation.speed===n} onClick={()=>dispatch({type:'CONTROL',speed:n})}>{n}×</button>)}</div><button className="ty-primary" onClick={takeControl}><Hand size={20}/><span>{state.automation.mode==='auto'?'Взять управление':'Управление'}</span></button><button className="ty-reset" aria-label="Начать демонстрацию заново" title="Начать заново" onClick={()=>{dispatch({type:'RESET'});setCard(true);}}><ArrowCounterClockwise size={19}/></button></div>
      <button className="ty-open ty-glass" aria-label="Открыть управление банкетом" onClick={()=>showPanel('plan')}><ListChecks size={23}/></button>
    </div>
    {notice&&<p className="ty-toast ty-glass" role="status">{notice}</p>}
    {panel&&<dialog className="ty-panel ty-glass" ref={dialog} aria-labelledby="ty-panel-title" onCancel={e=>{e.preventDefault();setPanel(null);}}>
      <header><div><small>TYNYSH · УПРАВЛЕНИЕ БАНКЕТОМ</small><h2 id="ty-panel-title">{state.event.title}</h2></div><button className="ty-close" aria-label="Закрыть управление" onClick={()=>setPanel(null)}><X size={22}/></button></header>
      <label className="ty-role">Роль<select value={state.role} onChange={e=>{dispatch({type:'ROLE',role:e.target.value});if(e.target.value==='staff')setPanel('tasks');}}><option value="admin">Администратор</option><option value="staff">Сотрудник · Данияр</option></select></label>
      <nav className="ty-tabs" aria-label="Разделы банкета">{tabs.filter(t=>admin||t[0]==='tasks').map(([id,label,Icon])=><button key={id} aria-pressed={panel===id} onClick={()=>setPanel(id)}><Icon size={18}/>{label}</button>)}</nav>
      <div className="ty-panel-body">
        {state.error&&<p className="ty-error" role="alert">{state.error}</p>}
        {panel==='plan'&&admin&&<><div className="ty-section-title"><h3>План и рассадка</h3><span>{state.event.guests}/48 гостей</span></div><div className="ty-presets">{[48,36].map(n=><button key={n} aria-pressed={state.event.guests===n} onClick={()=>dispatch({type:'GUESTS',guests:n})}>6 столов × {n/6}</button>)}</div><div className="ty-table-grid">{TYNYSH_TABLES.map(t=><button key={t.id} aria-pressed={state.selected===t.id} onClick={()=>select(t.id)}><Chair size={21}/><strong>Стол {t.id}</strong><small>{tableGuests(state,t.id)} гостей</small>{state.tasks.find(a=>a.table===t.id).done&&<Check className="ty-table-check" size={16}/>}</button>)}</div><div className="ty-selection"><strong>Стол {state.selected}</strong><span>{selected.done?'Сервировка готова':`Ответственный: ${member.name}`}</span></div><label className="ty-field">Меню<select value={state.event.menu} onChange={e=>dispatch({type:'MENU',menu:e.target.value})}>{Object.entries(TYNYSH_MENUS).map(([id,m])=><option key={id} value={id}>{m.name} · {tynyshMoney(m.price)}/гость</option>)}</select></label><button className="ty-primary ty-wide" onClick={()=>{dispatch({type:'PREPARE'});setPanel(null);setCard(true);}}>Начать подготовку<Play size={17}/></button><Booking state={state} dispatch={dispatch}/></>}
        {panel==='tasks'&&<><div className="ty-section-title"><h3>{admin?'Команда готовит зал':'Мои задачи'}</h3><span>{ready}/6 готовы</span></div><p className="ty-muted">{!admin&&state.phase==='seating'?'Подготовка начнётся после подтверждения плана администратором.':'Сотрудник подойдёт к столу с посудой и завершит сервировку. Готовность отобразится в зале.'}</p>{state.tasks.filter(t=>admin||t.staff==='daniyar').map(t=><article className={'ty-task'+(t.done?' done':'')} key={t.table}><span className="ty-task-number">{t.done?<Check size={19}/>:t.table}</span><div><strong>Сервировка стола {t.table}</strong><span>{t.done?'Завершено':tableGuests(state,t.table)+' гостей'}</span>{admin&&!t.done?<select aria-label={`Ответственный за стол ${t.table}`} value={t.staff} onChange={e=>dispatch({type:'ASSIGN',table:t.table,staff:e.target.value})}><option value="daniyar">Данияр</option><option value="aida">Аида</option></select>:<small>{TYNYSH_STAFF.find(a=>a.id===t.staff).name}</small>}</div>{!t.done&&<button disabled={state.phase!=='preparation'} aria-label={`Завершить сервировку стола ${t.table}`} onClick={()=>dispatch({type:'DONE',table:t.table})}><Check size={18}/></button>}</article>)}<button className="ty-primary ty-wide" disabled={state.phase==='ready'||(!admin&&state.phase==='seating')} onClick={()=>{if(state.phase==='seating')dispatch({type:'PREPARE'});else dispatch({type:'CONTROL',paused:false});setPanel(null);setCard(true);}}>Продолжить подготовку<Play size={17}/></button></>}
        {panel==='finance'&&admin&&<><div className="ty-finance"><span>Стоимость банкета</span><strong>{tynyshMoney(total.total)}</strong><small>{state.event.guests} гостей · {TYNYSH_MENUS[state.event.menu].name.toLowerCase()} меню</small></div><dl className="ty-totals"><div><dt>Получено</dt><dd>{tynyshMoney(total.income)}</dd></div><div><dt>{total.overpaid?'Переплата':'Осталось оплатить'}</dt><dd>{tynyshMoney(total.overpaid||total.balance)}</dd></div><div><dt>Расходы</dt><dd>{tynyshMoney(total.expenses)}</dd></div></dl><h3>Операции</h3>{state.payments.length?state.payments.map(p=><div className="ty-payment" key={p.id}>{p.kind==='income'?<ArrowDown size={18}/>:<ArrowUp size={18}/>}<span>{p.label}</span><strong>{p.kind==='income'?'+':'−'}{tynyshMoney(p.amount)}</strong></div>):<p className="ty-muted">Платежей пока нет. Добавьте первую операцию.</p>}<Payment dispatch={dispatch}/></>}
        {panel==='history'&&admin&&<><h3>История действий</h3><ol className="ty-history">{[...state.history].reverse().map((line,i)=><li key={state.history.length-i}><span>{String(state.history.length-i).padStart(2,'0')}</span><p>{line}</p></li>)}</ol></>}
      </div>
    </dialog>}
  </main>;
}
