import React, { useEffect, useRef, useState } from 'react';
import { Buildings, CaretDown, MagnifyingGlass, Bell, Microphone, MicrophoneSlash, VideoCamera, VideoCameraSlash, ChatCircleText, MonitorArrowUp, Minus, Plus, Crosshair, X, ArrowUpRight, ArrowLeft, ArrowRight, Check, CheckCircle, Circle, PaperPlaneTilt, Phone, PhoneDisconnect, Users, Target, Briefcase, MapPin, Info, Keyboard, Sun } from '@phosphor-icons/react';
import { statusClass } from './data';
import { worldDepartments as departments, worldPeople as people } from './world/data.js';
import { FLOOR_INFO } from './world/floors.js';
import { WorldScene } from './world/WorldScene.jsx';
import './world/world.css';
import './office.css';
import './reference-ui.css';



function Avatar({ person = people[0], size = 40 }) {return person.id === 'alexey' ? <span className="avatar avatar-reference" aria-hidden="true" style={{ '--avatar-size': `${size}px`, width: size, height: size }} /> : <span className="avatar initial" style={{ width: size, height: size, background: person.color + '21', color: person.color }} aria-hidden="true">{person.name.split(' ').map((n) => n[0]).join('')}</span>;}
function IconButton({ label, children, active, ...props }) {return <button className={'icon-button' + (active ? ' active' : '')} aria-label={label} title={label} {...props}>{children}</button>;}
export function App() {

  const [floorId, setFloorId] = useState(1);
  const switchFloor = (id) => {setMenu(null);setPanel(null);setSearchOpen(false);setView('office');api.current?.changeFloor(id);};
  const api = useRef(null),searchRef = useRef(null),panelRef = useRef(null);
  const [view, setView] = useState('office'),[panel, setPanel] = useState(null),[menu, setMenu] = useState(null),[query, setQuery] = useState(''),[searchOpen, setSearchOpen] = useState(false),[filter, setFilter] = useState('all');
  const [status, setStatus] = useState('Фокус'),[mic, setMic] = useState(false),[cam, setCam] = useState(false),[sharing, setSharing] = useState(false),[walk, setWalk] = useState(false),[zoom, setZoom] = useState(100),[toast, setToast] = useState(''),[showHelp, setShowHelp] = useState(false);
  const [messages, setMessages] = useState({}),[draft, setDraft] = useState(''),[call, setCall] = useState(null),[read, setRead] = useState(false),[evidence, setEvidence] = useState(''),[evidenceAdded, setEvidenceAdded] = useState(false),[promotion, setPromotion] = useState(false),[requestNote, setRequestNote] = useState('');
  const notice = (t) => setToast(t);
  useEffect(() => {if (toast) {const id = setTimeout(() => setToast(''), 4500);return () => clearTimeout(id);}}, [toast]);
  useEffect(() => {function key(e) {if (e.key === 'Escape') {setPanel(null);setMenu(null);setSearchOpen(false);setShowHelp(false);setCall(null);setView('office');}if (e.key === '/' && !['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName)) {e.preventDefault();searchRef.current?.focus();setSearchOpen(true);}}window.addEventListener('keydown', key);return () => window.removeEventListener('keydown', key);}, []);
  useEffect(() => {if (panel) panelRef.current?.focus();}, [panel?.type]);
  useEffect(() => {if (!showHelp && !call) return;const previous = document.activeElement;const dialog = document.querySelector('[role="dialog"]');const getButtons = () => [...dialog.querySelectorAll('button:not([disabled]),input,textarea,[tabindex="0"]')];getButtons()[0]?.focus();const trap = (e) => {if (e.key !== 'Tab') return;const items = getButtons(),first = items[0],last = items.at(-1);if (e.shiftKey && document.activeElement === first) {e.preventDefault();last?.focus();} else if (!e.shiftKey && document.activeElement === last) {e.preventDefault();first?.focus();}};dialog.addEventListener('keydown', trap);return () => {dialog.removeEventListener('keydown', trap);previous?.focus();};}, [showHelp, call]);
  const openPerson = (id) => {setPanel({ type: 'person', id });setView('office');setQuery('');setSearchOpen(false);setMenu(null);};
  const closePanel = () => {setPanel(null);setView('office');};
  const openView = (v) => {setView(v);setPanel(v === 'office' ? null : { type: v });setMenu(null);setSearchOpen(false);};
  const openChat = (id = 'anna') => {setPanel({ type: 'chat', id });setDraft('');setMenu(null);setView('office');};
  const selected = people.find((p) => p.id === panel?.id) || people[0],department = departments.find((d) => d.id === panel?.id);
  const q = query.toLocaleLowerCase('ru').trim(),foundPeople = people.filter((p) => (p.name + ' ' + p.role).toLowerCase().includes(q)),foundDepts = departments.filter((d) => (d.name + ' ' + d.purpose).toLowerCase().includes(q));
  const openDept = (id) => {setPanel({ type: 'department', id });setView('office');setSearchOpen(false);setQuery('');};
  const sendMessage = (e) => {e.preventDefault();if (!draft.trim()) return;setMessages((m) => ({ ...m, [panel.id]: [...(m[panel.id] || []), { text: draft.trim(), time: new Date().toLocaleTimeString('ru', { hour: '2-digit', minute: '2-digit' }) }] }));setDraft('');};
  const title = { team: 'Команда', growth: 'Моё развитие', department: department?.name, person: 'Профиль сотрудника', chat: 'Сообщения', notifications: 'Уведомления', promotion: 'Запрос на повышение', evidence: 'Подтверждение навыка' }[panel?.type];
  return <div className={'engine-stage'}><main className={'office-app' + ''}>
    {<WorldScene onFloor={setFloorId} onCompany={() => {setMenu('company');setPanel(null);setSearchOpen(false);}} api={api} onPerson={openPerson} onNotice={notice} onWalk={setWalk} onDept={openDept} onZoom={setZoom} status={status} walk={walk} selectedId={panel?.id} inputEnabled={!panel && !menu && !searchOpen && !showHelp && !call} />}
    {<header className="topbar"><div className="top-left">
      <button className="company floating" aria-label="Наш офис Демо" onClick={() => setMenu(menu === 'company' ? null : 'company')} aria-expanded={menu === 'company'}><Buildings size={25} /><strong>Наш офис</strong><CaretDown size={14} /><span className="demo-badge">Демо</span></button>
      <nav className="navigation floating" aria-label="Основная навигация">{[['office', 'Офис'], ['team', 'Команда'], ['growth', 'Развитие']].map(([id, label]) => <button key={id} onClick={() => openView(id)} aria-current={view === id ? 'page' : undefined} className={view === id ? 'selected' : ''}>{label}</button>)}</nav>
    </div><div className="top-right">
      <div className={'search floating' + (searchOpen ? ' focused' : '')}><MagnifyingGlass size={21} /><input ref={searchRef} placeholder="Найти человека или отдел" aria-label="Найти человека или отдел" value={query} onFocus={() => {setSearchOpen(true);setMenu(null);}} onChange={(e) => setQuery(e.target.value)} /><kbd>/</kbd></div>
      <button className="notification-button floating" aria-label="Уведомления" onClick={() => {setPanel({ type: 'notifications' });setRead(true);setMenu(null);}}><Bell size={23} />{!read && <i />}</button>
      <button className="profile-menu floating" aria-label="Мой профиль" aria-expanded={menu === 'profile'} onClick={() => setMenu(menu === 'profile' ? null : 'profile')}><Avatar size={34} /><CaretDown size={14} /></button>
    </div></header>}
    {searchOpen && <><button className="invisible-scrim" aria-label="Закрыть поиск" onClick={() => setSearchOpen(false)} /><div className="search-results floating"><div className="eyebrow">{q ? 'Результаты поиска' : 'Люди и отделы'}</div>
      {foundPeople.slice(0, q ? 6 : 3).map((p) => <button className="result-row" key={p.id} onClick={() => openPerson(p.id)}><Avatar person={p} size={35} /><span><strong>{p.name}</strong><small>{p.role}</small></span><i className={'status-dot ' + statusClass[p.status]} /></button>)}
      {!!foundDepts.length && <div className="eyebrow result-divider">Отделы</div>}{foundDepts.slice(0, 5).map((d) => <button className="result-row" key={d.id} onClick={() => openDept(d.id)}><span className="result-icon"><Buildings size={20} /></span><span><strong>{d.name}</strong><small>{d.short}</small></span><ArrowUpRight size={15} /></button>)}
      {!foundPeople.length && !foundDepts.length && <div className="empty-state"><MagnifyingGlass size={28} /><strong>Никого не нашли</strong><p>Попробуйте другое имя или название отдела.</p></div>}
    </div></>}
    {menu && <button className="invisible-scrim menu-scrim" aria-label="Закрыть меню" onClick={() => setMenu(null)} />}
    {menu === 'company' && <div className="company-dropdown floating"><div className="eyebrow">Рабочее пространство</div><strong>Наш офис</strong><p>{FLOOR_INFO[floorId - 1].name + ' · ' + floorId + ' этаж'}</p>{<div className="floor-menu" aria-label="Этажи офиса">{FLOOR_INFO.map((f) => <button key={f.id} className={floorId === f.id ? 'selected' : ''} aria-current={floorId === f.id ? 'true' : undefined} onClick={() => switchFloor(f.id)}><b>{f.id}</b><span>{f.name}<small>{f.id === floorId ? 'Вы здесь' : 'Перейти на этаж'}</small></span>{floorId === f.id ? <Check size={16} /> : <ArrowRight size={16} />}</button>)}</div>}<button className="text-button" onClick={() => {setMenu(null);setShowHelp(true);}}>{'Как перемещаться по офису'}<ArrowUpRight size={15} /></button><div className="demo-note">{'Демонстрационные данные. Изменения доступны до обновления страницы.'}</div></div>}
    {menu === 'profile' && <div className="profile-dropdown floating"><div className="profile-mini"><Avatar /><div><strong>Алексей Морозов</strong><small>Frontend-разработчик</small></div></div><button className="menu-line" onClick={() => openPerson('alexey')}><Users size={19} />Мой профиль<ArrowRight size={16} /></button><button className="menu-line" onClick={() => openView('growth')}><Target size={19} />Моё развитие<ArrowRight size={16} /></button><button className="menu-line" onClick={() => {setMenu(null);setShowHelp(true);}}><Keyboard size={19} />Управление офисом</button></div>}
    {panel && <aside ref={panelRef} tabIndex={-1} className="side-panel floating" aria-label={title}><div className="panel-heading"><h1>{title}</h1><IconButton label="Закрыть панель" onClick={closePanel}><X size={20} /></IconButton></div><div className="panel-body">
      {panel.type === 'person' && <><div className="person-hero"><Avatar person={selected} size={74} /><h2>{selected.name}{selected.id === 'alexey' && <span className="you-chip">Вы</span>}</h2><p>{selected.role}</p><span className={'status-pill ' + statusClass[selected.id === 'alexey' ? status : selected.status]}><i />{selected.id === 'alexey' ? status : selected.status}</span></div>
        <div className="button-row">{selected.id !== 'alexey' ? <><button className="primary" onClick={() => openChat(selected.id)}><ChatCircleText size={19} />Написать</button><button className="secondary" onClick={() => setCall(selected)}><Phone size={18} />Позвонить</button></> : <button className="primary" onClick={() => openView('growth')}><Target size={19} />Моё развитие</button>}</div>
        <section className="detail-section"><div className="eyebrow">Сейчас работает над</div><div className="task-card"><span className="small-icon"><Briefcase size={20} /></span><div><strong>{selected.task}</strong><small>Обновлено сотрудником · 12 минут назад</small></div></div></section>
        <section className="detail-section"><div className="eyebrow">Команда</div><button className="department-link" onClick={() => openDept(selected.department)}><Buildings size={20} /><span>{departments.find((d) => d.id === selected.department)?.name}</span><ArrowUpRight size={17} /></button></section>
        <section className="detail-section"><div className="eyebrow">Чем могу помочь</div><div className="chips">{(selected.department === 'engineering' ? ['Продукт', 'Разработка', 'Обратная связь'] : ['Вопросы отдела', 'Помощь коллегам', 'Обратная связь']).map((t) => <span key={t}>{t}</span>)}</div></section>
        <button className="wide-subtle" onClick={() => {api.current?.locate(selected.id);closePanel();}}><MapPin size={18} />Показать в офисе<ArrowRight size={17} /></button><p className="muted-note">Статус и текущая задача помогают выбрать удобный момент для общения.</p></>}
      {panel.type === 'department' && department && <><div className="department-intro"><span className="department-symbol"><Buildings size={28} /></span><span className="small-pill">{department.memberIds?.length ?? people.filter((p) => p.department === department.id).length} {department.memberIds ? 'участника · демо' : 'коллег'}</span><h2>{department.short}</h2><p>{department.purpose}</p></div>
        <section className="detail-section"><div className="eyebrow">За что отвечаем</div><ul className="responsibilities">{department.responsibilities.map((t) => <li key={t}><Check size={17} />{t}</li>)}</ul></section>
        <section className="detail-section"><div className="section-title"><h3>Сейчас в работе</h3><span>{department.tasks.length}</span></div>{department.tasks.map((t) => <div className="dept-task" key={t.title}><span className="task-status"><Circle size={17} /></span><div><strong>{t.title}</strong><small>{t.owner}</small><span className="small-pill">{t.status}</span></div></div>)}</section>
        <section className="detail-section"><div className="section-title"><h3>{department.memberIds ? 'Участники демо-встречи' : 'Люди отдела'}</h3></div>{people.filter((p) => department.memberIds ? department.memberIds.includes(p.id) : p.department === department.id).map((p) => <button className="result-row" key={p.id} onClick={() => openPerson(p.id)}><Avatar person={p} size={37} /><span><strong>{p.name}</strong><small>{p.role}</small></span><i className={'status-dot ' + statusClass[p.status]} /></button>)}</section><button className="primary full" onClick={() => {const contact = department.memberIds?.[0] || people.find((p) => p.department === department.id)?.id;if (contact) openChat(contact);else notice('Демо: контакт этого отдела пока не назначен.');}}><ChatCircleText size={19} />Связаться с отделом</button></>}
      {panel.type === 'team' && <><div className="section-intro"><h2>Все рядом.<br />Даже на расстоянии.</h2><p>11 коллег в нашем виртуальном офисе</p></div><div className="filter-tabs">{[['all', 'Все'], ['available', 'На связи'], ['departments', 'Отделы']].map(([id, t]) => <button key={id} className={filter === id ? 'selected' : ''} onClick={() => setFilter(id)}>{t}</button>)}</div>
        {filter === 'departments' ? departments.map((d) => <button className="department-tile" key={d.id} onClick={() => openDept(d.id)}><Buildings size={23} /><span><strong>{d.name}</strong><small>{d.short}</small></span><ArrowUpRight size={17} /></button>) : people.filter((p) => filter === 'all' || (p.id === 'alexey' ? status : p.status) === 'На связи').map((p) => <button className="team-row" key={p.id} onClick={() => openPerson(p.id)}><Avatar person={p} size={43} /><span><strong>{p.name}</strong><small>{p.task}</small><span className={'inline-status ' + statusClass[p.id === 'alexey' ? status : p.status]}><i />{p.id === 'alexey' ? status : p.status}</span></span><ArrowUpRight size={16} /></button>)}</>}
      {panel.type === 'growth' && <><div className="growth-intro"><span className="eyebrow">Ваш следующий шаг</span><h2>От уверенных решений<br />к большему влиянию.</h2><p>Frontend-разработчик</p></div><div className="career-track"><div><span className="track-node done"><Check size={13} /></span><small>Junior</small></div><i /><div className="current"><span className="track-node">2</span><small>Middle</small></div><i /><div><span className="track-node next">3</span><small>Senior</small></div><i /><div><span className="track-node">4</span><small>Lead</small></div></div>
        <div className="progress-card"><div><strong>Готовность к Senior</strong><span>{evidenceAdded ? '6 из 6' : '5 из 6'}</span></div><div className="progress-bar"><i style={{ width: evidenceAdded ? '100%' : '83.33%' }} /></div><p>{evidenceAdded ? 'Все подтверждения собраны. Можно начать обсуждение.' : 'Осталось подтвердить опыт наставничества.'}</p></div><div className="section-title"><h3>Требования к уровню</h3><span>6 критериев</span></div>
        {[
            ['Архитектура frontend', 'Самостоятельно проектировать сложные модули', 'Ревью архитектуры · подтверждено'],
            ['Качество и надёжность', 'Обеспечивать тестируемость и устойчивость кода', 'Релизы за 2 квартала · подтверждено'],
            ['Результат для продукта', 'Доводить инициативы до измеримого результата', '3 завершённых проекта'],
            ['Командная работа', 'Договариваться и давать полезную обратную связь', 'Обратная связь 360° · подтверждено'],
            ['Опыт и самостоятельность', 'Брать ответственность за направление', '12 месяцев на уровне Middle'],
            ['Наставничество', 'Помочь коллеге вырасти в самостоятельности', evidenceAdded ? 'Подтверждение добавлено' : 'Добавьте пример и ссылку на результат']].
            map(([name, desc, proof], i) => <div className={'criterion ' + (i === 5 && !evidenceAdded ? 'pending' : '')} key={name}>{i === 5 && !evidenceAdded ? <Circle size={21} /> : <CheckCircle size={21} weight="fill" />}<div><strong>{name}</strong><p>{desc}</p><small>{proof}</small>{i === 5 && !evidenceAdded && <button className="text-button" onClick={() => setPanel({ type: 'evidence' })}>Добавить подтверждение<Plus size={14} /></button>}</div></div>)}
        <div className="manager-note"><Info size={18} /><p>Повышение обсуждается с руководителем. Критерии помогают сделать разговор конкретным и прозрачным.</p></div><button className="primary full" disabled={promotion} onClick={() => setPanel({ type: 'promotion' })}>{promotion ? <CheckCircle size={18} /> : <ArrowUpRight size={18} />} {promotion ? 'Запрос отправлен' : 'Запросить повышение'}</button></>}
      {panel.type === 'evidence' && <form onSubmit={(e) => {e.preventDefault();if (evidence.trim().length < 15) return;setEvidenceAdded(true);setPanel({ type: 'growth' });notice('Подтверждение добавлено в ваш карьерный профиль');}}><button type="button" className="back-link" onClick={() => setPanel({ type: 'growth' })}><ArrowLeft size={16} />К моему развитию</button><div className="section-intro"><h2>Наставничество</h2><p>Расскажите, кому вы помогли и какого результата удалось достичь.</p></div><label className="field-label" htmlFor="evidence">Пример из практики</label><textarea id="evidence" minLength={15} required value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="Например: помог коллеге освоить проект и самостоятельно выпустить первую задачу. Ссылка на результат…" rows={7} /><p className="muted-note">Минимум 15 символов. В демо подтверждение сохраняется в текущем сеансе.</p><button className="primary full" type="submit">Добавить подтверждение<Check size={18} /></button></form>}
      {panel.type === 'promotion' && <form onSubmit={(e) => {e.preventDefault();setPromotion(true);setPanel({ type: 'growth' });notice('Демо-запрос создан. Следующий шаг — встреча с руководителем.');}}><button type="button" className="back-link" onClick={() => setPanel({ type: 'growth' })}><ArrowLeft size={16} />К моему развитию</button><div className="section-intro"><h2>Давайте обсудим<br />следующий уровень.</h2><p>Middle → Senior · Frontend</p></div><div className="task-card"><Avatar person={people[3]} size={40} /><div><strong>Артём Беляев</strong><small>Получатель · руководитель продукта</small></div></div>{!evidenceAdded && <div className="manager-note"><Info size={19} /><p>Наставничество пока не подтверждено. Это можно обсудить на встрече или добавить пример в профиль.</p></div>}<label className="field-label" htmlFor="request-note">Что хотите обсудить</label><textarea id="request-note" required minLength={10} rows={5} placeholder="Главные результаты, новая ответственность и ваши ожидания…" value={requestNote} onChange={(e) => setRequestNote(e.target.value)} /><div className="demo-note">Это демонстрация. Запрос не отправляется реальным людям.</div><button type="submit" className="primary full">Отправить запрос<ArrowUpRight size={18} /></button></form>}
      {panel.type === 'chat' && <div className="chat-layout"><button className="chat-recipient" onClick={() => openPerson(selected.id)}><Avatar person={selected} /><span><strong>{selected.name}</strong><small><i className={'status-dot ' + statusClass[selected.status]} />{selected.status}</small></span><ArrowUpRight size={17} /></button><div className="chat-history"><div className="chat-date">Сегодня · демо-диалог</div><div className="message incoming">Привет! Если понадобится помощь по моей задаче — я рядом.<time>10:24</time></div>{(messages[selected.id] || []).map((m, i) => <div className="message outgoing" key={i}>{m.text}<time>{m.time}<Check size={11} /></time></div>)}</div><form className="chat-compose" onSubmit={sendMessage}><input aria-label="Сообщение" placeholder="Написать сообщение…" value={draft} onChange={(e) => setDraft(e.target.value)} /><IconButton label="Отправить сообщение" disabled={!draft.trim()} type="submit"><PaperPlaneTilt size={20} /></IconButton></form><p className="chat-disclaimer">Локальный демо-чат · сообщения остаются в этом сеансе</p></div>}
      {panel.type === 'notifications' && <><div className="notification-item"><span className="notice-icon"><Target size={22} /></span><div><strong>Ваш следующий шаг</strong><p>5 из 6 критериев для уровня Senior уже подтверждены.</p><button className="text-button" onClick={() => openView('growth')}>Открыть развитие<ArrowUpRight size={15} /></button><small>Сегодня, 10:30</small></div></div><div className="notification-item"><span className="notice-icon blue"><Users size={22} /></span><div><strong>Продуктовое ревью</strong><p>Сегодня в 15:00 встречаемся в переговорной.</p><button className="text-button" onClick={() => openDept('meeting-3')}>Посмотреть встречу<ArrowUpRight size={15} /></button><small>Сегодня, 09:45</small></div></div><div className="demo-note">Пример уведомлений рабочего пространства</div></>}
    </div></aside>}
    {<div className="bottom-dock floating"><button className="dock-profile" onClick={() => openPerson('alexey')}><Avatar /><span><strong>Алексей<CaretDown size={11} /></strong><small>{walk ? 'Иду по офису' : 'Авторизация'}</small></span></button>
      <div className="status-control"><button className="status-button" aria-expanded={menu === 'status'} onClick={() => setMenu(menu === 'status' ? null : 'status')}><i className={'status-dot ' + statusClass[status]} />{status}<CaretDown size={13} /></button>{menu === 'status' && <div className="status-dropdown floating"><div className="eyebrow">Мой статус</div>{Object.keys(statusClass).map((s) => <button key={s} onClick={() => {setStatus(s);setMenu(null);notice('Ваш статус: ' + s);}}><i className={'status-dot ' + statusClass[s]} /><span>{s}</span>{status === s && <Check size={16} />}</button>)}</div>}</div><span className="dock-divider" />
      <IconButton label={mic ? 'Выключить микрофон' : 'Включить микрофон'} className={'icon-button ' + (!mic ? 'muted-control' : '')} onClick={() => {setMic(!mic);notice('Демо: микрофон ' + (!mic ? 'включён' : 'выключен') + '. Устройства не подключены.');}}>{mic ? <Microphone size={23} /> : <MicrophoneSlash size={23} />}</IconButton>
      <IconButton label={cam ? 'Выключить камеру' : 'Включить камеру'} className={'icon-button ' + (!cam ? 'muted-control' : '')} onClick={() => {setCam(!cam);notice('Демо: камера ' + (!cam ? 'включена' : 'выключена') + '. Устройства не подключены.');}}>{cam ? <VideoCamera size={24} /> : <VideoCameraSlash size={24} />}</IconButton>
      <IconButton label="Открыть сообщения" active={panel?.type === 'chat'} onClick={() => openChat()}><ChatCircleText size={24} /></IconButton><IconButton label={sharing ? 'Остановить демонстрацию' : 'Демонстрация экрана'} active={sharing} onClick={() => {setSharing(!sharing);notice(sharing ? 'Демонстрация завершена' : 'Демо-режим демонстрации экрана. Экран не передаётся.');}}><MonitorArrowUp size={24} /></IconButton>
    </div>}

    {<><div className="view-controls"><div className="zoom-control floating"><IconButton label="Уменьшить масштаб" disabled={zoom <= 65} onClick={() => api.current?.zoom(-.1)}><Minus size={17} /></IconButton><button className="zoom-value" onClick={() => api.current?.reset()} title="Сбросить масштаб">{zoom}%</button><IconButton label="Увеличить масштаб" disabled={zoom >= 210} onClick={() => api.current?.zoom(.1)}><Plus size={17} /></IconButton></div><button className="center-control floating" aria-label="Камера к персонажу" title="Камера к персонажу" onClick={() => api.current?.reset()}><Crosshair size={23} /></button></div><button className="help-button" onClick={() => setShowHelp(true)}><Keyboard size={16} /><span>WASD · Управление</span></button></>}
    {toast && <div className="toast floating" role="status"><CheckCircle size={19} /><span>{toast}</span><button aria-label="Закрыть уведомление" onClick={() => setToast('')}><X size={16} /></button></div>}
    {showHelp && <div className="modal-backdrop" onClick={() => setShowHelp(false)}><div className="help-modal floating" role="dialog" aria-modal="true" aria-label="Управление офисом" onClick={(e) => e.stopPropagation()}><IconButton label="Закрыть подсказку" onClick={() => setShowHelp(false)}><X size={20} /></IconButton><span className="department-symbol"><Buildings size={29} /></span><h2>Осмотритесь. Вы в офисе.</h2><p>Небольшие действия, чтобы почувствовать пространство.</p>{[['WASD / ↑↓←→', 'Ходить по офису, в том числе в русской раскладке'], ['Shift', 'Идти быстрее'], ['E', 'Открыть дверь, сесть или воспользоваться лифтом'], ['Home', 'Вернуть камеру к персонажу и сбросить масштаб'], ['Esc', 'Остановиться и закрыть окно'], ['Клик', 'По свободному полу — пройти к точке'], ['Клик', 'По коллеге или названию отдела — узнать больше'], ['Камера', 'Следует за вашим персонажем'], ['Колесо', 'Приблизить или отдалить'], ['/', 'Найти человека или отдел']].map(([key, text], i) => <div className="help-row" key={i}><kbd>{key}</kbd><span>{text}</span></div>)}<button className="primary full" onClick={() => setShowHelp(false)}>Всё понятно<ArrowRight size={18} /></button></div></div>}
    {call && <div className="modal-backdrop"><div className="call-modal floating" role="dialog" aria-modal="true" aria-label="Демо-звонок"><span className="eyebrow">Демонстрация звонка</span><Avatar person={call} size={84} /><h2>{call.name}</h2><p>Здесь будет разговор с коллегой.<br />Аудио и видео в этом демо не передаются.</p><button className="end-call" onClick={() => setCall(null)}><PhoneDisconnect size={23} />Завершить</button></div></div>}
  </main></div>;
}
