export const departments = [
  { id: 'engineering', name: 'Разработка', short: 'Продукт и технологии', x: -7.8, z: -7.2, people: 4, purpose: 'Превращаем идеи в надёжный продукт, которым удобно пользоваться каждый день.', responsibilities: ['Разработка веб-приложения', 'Архитектура и качество кода', 'Стабильность и безопасность'], tasks: [{title:'Новый сценарий авторизации',owner:'Алексей Морозов',status:'В работе'}, {title:'Дизайн-система продукта',owner:'Анна Смирнова',status:'На проверке'}, {title:'API профиля сотрудника',owner:'Марк Ким',status:'В работе'}] },
  { id: 'meeting', name: 'Переговорная', short: 'Место для совместных решений', x: 0, z: -8, people: 1, purpose: 'Обсуждаем сложные вопросы, показываем результаты и договариваемся о следующем шаге.', responsibilities: ['Командные встречи', 'Демонстрации продукта', 'Обсуждение решений'], tasks:[{title:'Продуктовое ревью · 15:00',owner:'Команда продукта',status:'Сегодня'}] },
  { id: 'marketing', name: 'Маркетинг', short: 'Рассказываем о продукте', x: 7.9, z: -7.2, people: 2, purpose: 'Помогаем будущим клиентам узнать о продукте и понять, какую пользу он принесёт.', responsibilities: ['Исследования аудитории', 'Запуски и коммуникации', 'Контент и привлечение клиентов'], tasks:[{title:'Запуск осенней кампании',owner:'Полина Лебедева',status:'В работе'}, {title:'Истории наших клиентов',owner:'Денис Волков',status:'На проверке'}] },
  { id: 'people', name: 'Люди и культура', short: 'Помогаем людям расти', x: -8, z: 1.6, people: 2, purpose: 'Создаём среду, в которой каждый понимает свою роль, получает поддержку и видит возможности роста.', responsibilities: ['Адаптация и поддержка', 'Развитие и карьерные треки', 'Культура и обратная связь'], tasks:[{title:'Карьерные треки: ревью',owner:'София Орлова',status:'В работе'}, {title:'Встречи с новыми коллегами',owner:'Илья Петров',status:'Сегодня'}] },
  { id: 'support', name: 'Поддержка', short: 'Рядом с нашими клиентами', x: 8, z: 1.6, people: 2, purpose: 'Помогаем клиентам решать вопросы и передаём их обратную связь команде продукта.', responsibilities: ['Помощь клиентам', 'База знаний', 'Обратная связь о продукте'], tasks:[{title:'Обновление базы знаний',owner:'Никита Соколов',status:'В работе'}, {title:'Вопросы по интеграциям',owner:'Ева Иванова',status:'В работе'}] },
];
export const people = [
  {id:'alexey',name:'Алексей Морозов',first:'Алексей',role:'Frontend-разработчик',department:'engineering',status:'Фокус',task:'Новый сценарий авторизации',x:-9.3,z:-3.7,color:'#355a89',hair:'#352e2b',skin:'#d3a37b',angle:Math.PI},
  {id:'anna',name:'Анна Смирнова',first:'Анна',role:'Продуктовый дизайнер',department:'engineering',status:'На связи',task:'Дизайн-система продукта',x:-5.6,z:-4.8,color:'#a2787c',hair:'#a96830',skin:'#e5b78b',angle:Math.PI/2},
  {id:'mark',name:'Марк Ким',first:'Марк',role:'Backend-разработчик',department:'engineering',status:'Фокус',task:'API профиля сотрудника',x:-7.3,z:-.8,color:'#327f93',hair:'#25272d',skin:'#dcb491',angle:Math.PI},
  {id:'artem',name:'Артём Беляев',first:'Артём',role:'Руководитель продукта',department:'meeting',status:'На встрече',task:'Планирование следующего релиза',x:-.4,z:-6.7,color:'#b17242',hair:'#3e312c',skin:'#c99574',angle:0},
  {id:'polina',name:'Полина Лебедева',first:'Полина',role:'Маркетолог',department:'marketing',status:'На связи',task:'Запуск осенней кампании',x:7.9,z:-5.8,color:'#536ba3',hair:'#b87739',skin:'#e4b185',angle:0},
  {id:'denis',name:'Денис Волков',first:'Денис',role:'Контент-редактор',department:'marketing',status:'Фокус',task:'Истории наших клиентов',x:9.9,z:-3.5,color:'#65706a',hair:'#252b31',skin:'#d9ac88',angle:-Math.PI/2},
  {id:'sofia',name:'София Орлова',first:'София',role:'People Partner',department:'people',status:'На связи',task:'Карьерные треки: ревью',x:-6,z:4.6,color:'#bc8564',hair:'#ceb164',skin:'#e2b48c',angle:-.5},
  {id:'ilya',name:'Илья Петров',first:'Илья',role:'Специалист по адаптации',department:'people',status:'Перерыв',task:'Перерыв на кофе',x:-9.1,z:4.6,color:'#4c7486',hair:'#704a32',skin:'#d7a87c',angle:.6},
  {id:'nikita',name:'Никита Соколов',first:'Никита',role:'Специалист поддержки',department:'support',status:'На связи',task:'Обновление базы знаний',x:6.5,z:3.4,color:'#527f88',hair:'#333035',skin:'#a87b59',angle:0},
  {id:'eva',name:'Ева Иванова',first:'Ева',role:'Специалист поддержки',department:'support',status:'Фокус',task:'Вопросы по интеграциям',x:7.3,z:6.1,color:'#81649b',hair:'#573727',skin:'#d6a880',angle:Math.PI},
  {id:'roman',name:'Роман Власов',first:'Роман',role:'QA-инженер',department:'engineering',status:'Перерыв',task:'Перерыв на кофе',x:-1.7,z:5,color:'#353f54',hair:'#29262b',skin:'#c39173',angle:.3},
];
export const statusClass = {'На связи':'available','Фокус':'focus','На встрече':'meeting','Перерыв':'away'};
